<!DOCTYPE html>
<html>
	<head>
		<title>Targeted Case Management Service Plan</title>
		<link rel="stylesheet" type="text/css" href="<?php echo $GLOBALS['webroot']; ?>/interface/themes/style_oemr.css">
		<link rel="stylesheet" type="text/css" href="<?php echo $this->rootDirectory ?>/forms/TCMAssessment/style.css">
		<script type="text/javascript" src="<?php echo $this->rootDirectory; ?>/forms/TCMAssessment/js/modernizr-custom-2.6.2.js"></script>
		<script type="text/javascript">
			Modernizr.load({
				test: Modernizr.inputtypes.date,
				nope: [
					'<?php echo $GLOBALS['webroot']; ?>/library/js/jquery-ui-1.8.21.custom.min.js',
					'<?php echo $GLOBALS['webroot']; ?>/library/css/jquery-ui-1.8.21.custom.css'
				],
				both : [
					'<?php echo $GLOBALS['webroot']; ?>/library/js/jquery-1.9.1.min.js',
					'<?php echo $this->rootDirectory; ?>/forms/TCMAssessment/js/knockout-2.2.1.js',
					'<?php echo $this->rootDirectory; ?>/forms/TCMServicePlan/js/ServicePlanSubModels.js',
					'<?php echo $this->rootDirectory; ?>/forms/TCMServicePlan/js/ServicePlan.js',
					'<?php echo $this->rootDirectory; ?>/forms/TCMServicePlan/js/ServicePlanViewModel.js'
				],
				complete: function () {
					$(document).ready(function() {
						if (typeof jQuery.ui !== 'undefined') {
							$('input[type=date]').datepicker({
								dateFormat: 'yyyy-mm-dd'
							}); 
						}

						ServicePlanVM = new ServicePlanViewModel;
						ServicePlanVM.Load({
							AjaxUri: '<?php echo $this->rootDirectory; ?>/forms/TCMServicePlan/ajax.php',
							WebRoot: '<?php echo $GLOBALS['webroot']; ?>',
							ExitUri: '<?php echo $GLOBALS['form_exit_url']; ?>',
							ServicePlanId: '<?php echo $this->servicePlanId; ?>',
							TestMode: false
						});
						ko.applyBindings(ServicePlanVM);
					});
				}
			});
		</script>
	</head>
	<body class="bgcolor2">
		<div id="activityWait" data-bind="visible: ActivityWait() !== false">
			<div>
				<span data-bind="text: ActivityWait">Initializing</span>
			</div>
		</div>
		<div id="hoverMenu">
			<div>
				<div class="css_button" data-bind="click: Exit"><span>Cancel</span></div>
			</div>
		</div>
		<div class="contentWraper">
			<h1>Targeted Case Management Service Plan</h1>
			<div id="formAlert" data-bind="visible: ErrorAlert() !== false">
				<p data-bind="text: ErrorAlert"></p>
			</div>
			<div class="form-section">
				<table>
					<tbody>
						<tr>
							<th>Service Plan Type</th>
							<td colspan="3" data-bind="text: ServicePlan.TypeDisplay"></td>
						</tr>
						<tr>
							<th style="width: 25%">Clients Name</th>
							<td style="width: 25%" data-bind="text: ServicePlan.ClientName"></td>
							<th style="width: 25%">Date of Birth</th>
							<td style="width: 25%" data-bind="text: ServicePlan.ClientBirth"></td>
						</tr>
						<tr>
							<th>Medicaid #</th>
							<td data-bind="text: ServicePlan.MedicaidId"></td>
							<td colspan="2"></td>
						</tr>
						<tr>
							<th>Targeted Case Manager</th>
							<td data-bind="text: ServicePlan.CaseManagerName"></td>
							<th>Supervisor</th>
							<td data-bind="text: ServicePlan.CaseManagerSupervisorName"></td>
						</tr>
						<tr>
							<th>Written Date</th>
							<td data-bind="text: ServicePlan.DateWritten"></td>
							<th>Completion Date</th>
							<td data-bind="text: ServicePlan.DateComplete"></td>
						</tr>
					</tbody>
				</table>
			</div>
			<div class="form-section">
				<table>
					<thead>
						<tr>
							<th colspan="3">
								<span class="section-title">Diagnosis</span>
							</th>
						</tr>
						<tr data-bind="visible: ServicePlan.DiagnosisActive().length > 0">
							<th style="width: 10%">Axis</th>
							<th style="width: 15%">Code</th>
							<th style="width: 74%">Description</th>
						</tr>
					</thead>
					<tbody data-bind="foreach: ServicePlan.Diagnosis">
						<tr>
							<td data-bind="text: AxisDisplay()"></td>
							<td data-bind="text: Code"></td>
							<td data-bind="text: Description"></td>
						</tr>
					</tbody>
					<tfoot>
						<tr>
							<th colspan="2">
								Source of Diagnosis
								<span class="section-subtitle">(include date & clinician)</span>
							</th>
							<td style="width: 75%" data-bind="text: ServicePlan.DiagnosisSource"></td>
						</tr>
					</tfoot>
				</table>
			</div>
			<div class="form-section">
				<table>
					<thead>
						<tr>
							<th><span class="section-title">Current Service Needs</span></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td data-bind=""></td>
						</tr>
					</tbody>
				</table>
			</div>
			<h1>Goals/Objectives</h1>
			<div data-bind="foreach: ServicePlan.Problems">
				<div class="form-section">
					<table>
						<thead>
							<tr>
								<th style="width: 16%;">Functional Area</th>
								<td data-bind="text: Area"></td>
							</tr>
						</thead>
						<tbody>
							<tr>
								<th>Problem</th>
								<td data-bind="text: Problem"></td>
							</tr>
						</tbody>
					</table>
					<div class="sourcesLink">
						<table>
							<thead>
								<tr>
									<th colspan="2" style="text-align: center; width: 100%;">Goals &amp; Objectives</th>
								</tr>
							</thead>
							<tbody data-bind="foreach: Goals">
								<tr>
									<th style="width: 16%;">Goal</th>
									<td data-bind="text: Goal"></td>
								</tr>
								<tr>
									<td colspan="2">
										<div class="sourcesLink" style="margin: 5px;">
											<table>
												<thead>
													<tr>
														<th colspan="3" style="text-align: center;">Objectives</th>
													</tr>
												</thead>
												<tbody data-bind="foreach: Objectives">
													<tr>
														<td rowspan="3" style="width: 60%;" data-bind="text: Objective"></td>
														<th>Target Date</th>
														<td style="width: 20%;" data-bind="text: TargetDate"></td>
													</tr>
													<tr>
														<th>Status</th>
														<td data-bind="text: StatusDisplay()"></td>
													</tr>
													<tr>
														<th>Progress Rating</th>
														<td data-bind="text: ProgressRate"></td>
													</tr>
												</tbody>
											</table>
										</div>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
					<table>
						<tbody>
							<tr>
								<th style="width: 16%;">Activities</th>
								<td data-bind="text: Activities"></td>
							</tr>
						</tbody>
					</table>
					<div class="sourcesLink">
						<table>
							<thead>
								<tr>
									<th colspan="3" style="text-align: center;">Agency / Agent Responsible</th>
								</tr>
								<tr data-bind="visible: AgentsActive().length > 0">
									<th>Type</th>
									<th>Agency</th>
									<th>Agent</th>
								</tr>
							</thead>
							<tbody data-bind="foreach: Agents">
								<tr>
									<td style="width: 20%;" data-bind="text: TypeDisplay()"></td>
									<td data-bind="text: Agency"></td>
									<td data-bind="text: Agent"></td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
			<div id="section-discharge" class="form-section">
				<table>
					<thead>
						<tr>
							<th>Discharge Plan</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>1. Upon completion of TCM activities, the service plan will be reviewed with the client/family for current status of each objective, referrals/resources provided and need for any additional services.</td>
						</tr>
						<tr>
							<td>2. When reported progress ratings are a <span style="border-bottom: 1px solid black; display: inline-block; text-align: center ; width: 2em;" data-bind="value: ServicePlan.DischargeRate"></span> or above on each of the objectives listed above or when all service needs are met, a closing letter will be completed and case will be closed within 30 days.</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</body>
</html>